//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public string uname { get; set; }
        public long contact { get; set; }
        public Nullable<System.DateTime> bday { get; set; }
        public Nullable<short> age { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string pwd { get; set; }
        public string path { get; set; }
    }
}
