//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductData
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int UserId { get; set; }
        public string Category { get; set; }
        public string SmallDescription { get; set; }
        public string SmallImage { get; set; }
        public string LongDescription { get; set; }
        public string LongImage { get; set; }
        public string Tags { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
